ReviewWebsite/Models/ViewModel/FormViewModel.cs
using Microsoft.AspNetCore.Mvc;
using ReviewWebsite.Models.Db;
using System.ComponentModel.DataAnnotations;
using System.Data;

namespace ReviewWebsite.Models.ViewModel
{
    public class FormViewModel
    {
        
        public string Data { get; set; }

        public String FormId { get; set; }

        public String Name { get; set; }

        public int Year { get; set; }

        public String UpdateTime { get; set; }
    }
}

ReviewWebsite/Controllers/FormController.cs
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;
using Microsoft.IdentityModel.Tokens;
using Microsoft.SqlServer.Server;
using ReviewWebsite.Data;
using ReviewWebsite.Helpers;
using ReviewWebsite.Models.Db;
using ReviewWebsite.Models.ViewModel;
using ReviewWebsite.Models.ViewModel.Request;
using System;
using System.Text.Json;

namespace ReviewWebsite.Controllers
{   /*
        1. 建立標單時,如果標題或是item 都是空時需要保留嗎?
        2. KPI連動是要連動到哪個資料庫
     
     
     */
    public class FormController : Controller
    {
        private readonly AppDbContext _context;

        public FormController(AppDbContext context)
        {
            _context = context;
        }

        // GET: Form
        public async Task<IActionResult> Index()
        {
            var model = await _context.FormList.ToListAsync();
            return this.ResolveView(nameof(Index), model);
        }

        // GET: Form/Create
        [HttpGet]
        public async Task<IActionResult> Create()
        {

            var form = await _context.Form.OrderByDescending(f => f.CreateTime).FirstOrDefaultAsync();
            if (form == null)
            {
                form = new Form()
                {
                    FormId = IdGenerator.GenerateUnitId(),

                    Data = JsonSerializer.Serialize(new List<List<object>>
                {
                    new List<object> { (DateTime.Now.Year-1911).ToString(),"新評鑑表單","","","","" },
                    new List<object> { "查核指標", "查核標準", "總分","應檢附資料", "評核基準","KPI連動" },
                })
                };
            }
            ViewData["Title"] = "新建表單";
            ViewData["Units"] = await _context.Unit.ToListAsync();
            return View("CreateOrEdit", form);
        }


        [HttpPost]
        [Consumes("application/json")]
        public async Task<IActionResult> Create([FromBody] FormViewModel formViewModel)
        {
            if (formViewModel == null ||
                formViewModel.Data.IsNullOrEmpty())
            {
                return this.ResponseJson(ControllerExtensions.RESPONCE_CODE_400);
            }

            var form = new Form()
            {
                FormId = IdGenerator.GenerateUnitId(),
                Data = formViewModel.Data

            };
            var formListData = new FormList()
            {
                FormListId = IdGenerator.GenerateUnitId(),
                FormId = form.FormId,
                Name = formViewModel.Name,
                Year = formViewModel.Year,
            };

            using (var transaction = await _context.Database.BeginTransactionAsync())
            {
                try
                {
                    await _context.Form.AddAsync(form);
                    await _context.FormList.AddAsync(formListData);
                    await _context.SaveChangesAsync();
                    await transaction.CommitAsync();
                    return this.ResponseJson(ControllerExtensions.RESPONCE_CODE_200);
                }
                catch (Exception ex)
                {
                    await transaction.RollbackAsync();
                    return this.ResponseJson(ControllerExtensions.RESPONCE_CODE_500, message: ex.Message);
                }
            }
        }

        //GET: Users/Edit/5
        [HttpGet]
        public async Task<IActionResult> Edit(string id)
        {
            if (id == null)
            {
                return RedirectToAction(nameof(Index));
            }
            var form = await _context.Form.FirstOrDefaultAsync(m => m.FormId == id);
            ViewData["Title"] = "編輯表單";
            return View("CreateOrEdit", form);
        }

        [HttpPost]
        [Consumes("application/json")]
        public async Task<IActionResult> Edit([FromBody] FormViewModel formViewModel)
        {

            if (formViewModel == null ||
                formViewModel.Data.IsNullOrEmpty())
            {
                return this.ResponseJson(ControllerExtensions.RESPONCE_CODE_400);
            }
            using (var transaction = await _context.Database.BeginTransactionAsync()) // 開始非同步交易
            {
                try
                {
                    // 更新 Form 表
                    var form = await _context.Form.FirstOrDefaultAsync(p => p.FormId == formViewModel.FormId);
                    if (form == null) {
                        return this.ResponseJson(ControllerExtensions.RESPONCE_CODE_400);
                    }

                    if (DateTime.Parse(formViewModel.UpdateTime).TotalSeconds() != form.UpdateTime.TotalSeconds()) {
                        return this.ResponseJson(ControllerExtensions.RESPONCE_CODE_501);
                    }
           
                    form.Data = formViewModel.Data;
                    form.UpdateTime = DateTime.Now;
                 
                    // 更新 FormList 表
                    var formList = await _context.FormList.FirstOrDefaultAsync(p => p.FormId == formViewModel.FormId);
                    if (formList == null)
                    {
                        return this.ResponseJson(ControllerExtensions.RESPONCE_CODE_400);
                    }
                    formList.Name = formViewModel.Name;
                    formList.Year = formViewModel.Year;
                    formList.UpdateTime = DateTime.Now;

                    // 儲存所有變更
                    await _context.SaveChangesAsync();
                    await transaction.CommitAsync();
                    return this.ResponseJson(ControllerExtensions.RESPONCE_CODE_200);
                }
                catch (Exception ex)
                {
                    // 若有錯誤，回滾交易
                    await transaction.RollbackAsync();
                    return this.ResponseJson(ControllerExtensions.RESPONCE_CODE_500,message:ex.Message);

                }
            }

        }

    }
}

ReviewWebsite/Views/Form/CreateOrEdit.cshtml
@using ReviewWebsite.Models.Db
@model ReviewWebsite.Models.Db.Form

@{
    Layout = "_Layout";
    List<Unit> units = ViewData["Units"] as List<Unit> ?? new List<Unit>();
}
@section Css {
    <link rel="stylesheet" href="~/css/feature/form.css" />
}

@section Scripts {
    <script src="~/js/feature/form/create_edit.js" asp-append-version="true"></script>
}
<div>
    <span id="FormId" hidden>@Model.FormId</span>
    <span id="Data" hidden>@Model.Data</span>
    <span id="UpdateTime" hidden>@Model.UpdateTime</span>
</div>
<div class="card shadow-sm">
    <div class="card-header-tab d-flex justify-content-between pe-3 ps-3 pt-3">
        <a asp-action="Index" type="button" class="btn btn-primary h2 m-0" asp-controller="Form">返回</a>
        <span class="h5 m-0">@ViewData["Title"]</span>
        <button type="button" class="btn btn-success h2 m-0" id="save">存儲</button>
    </div>
    <div class="card-body">
        <div id="spreadsheet" class="scroll-container"></div>
    </div>
</div>

@* model *@
<div class="modal fade" id="selectUnitModal" tabindex="-1" role="dialog" aria-labelledby="exampleModalLabel" aria-hidden="true">
    <div class="modal-dialog" role="document">
        <div class="modal-content">
            <div class="modal-header">
                <p class="modal-title h6" id="exampleModalLabel">KPI連動</p>
            </div>
            <div class="modal-body">
                <ul id="buttonContainer" class="d-flex flex-wrap gap-2">
                    @for (int i = 0; i < units.Count(); i++)
                    {
                        <li class="selectable_item" data-id="@units[i].UnitId">@units[i].Name</li>
                    }
                </ul>
                <div class="form-group d-flex justify-content-end mt-3">
                    <button id="confirmUnit" value="確定" class="btn btn-primary me-2">確定</button>
                    <button type="button" class="btn btn-secondary" data-bs-dismiss="modal">取消</button>
                </div>
            </div>
        </div>
    </div>
</div>

ReviewWebsite/Views/Form/Index.cshtml
@model IEnumerable<ReviewWebsite.Models.Db.FormList>

@{
    Layout = "_ManageLayout";
}
@section Css {
    
}
@section Scripts {
   
}
<div id="content">
    @await Html.PartialAsync("_Index", Model)
</div>

ReviewWebsite/Views/Form/_Index.cshtml
@model IEnumerable<ReviewWebsite.Models.Db.FormList>


<meta name="dynamic-styles" data-href="/css/feature/form.css" />
<meta name="dynamic-scripts" data-src="/js/feature/form/index.js" />

<div class="card text-start">
    <div class="card-body">
        <div class="text-end mb-2">
            <a asp-action="Create" type="button" class="btn btn-primary" asp-controller="Form">新增表單</a>
        </div>
        <table class="table table-striped list p-0" id="formTable">
            <thead>
                <tr>
                    <th>
                        #
                    </th>
                    <th>
                        @Html.DisplayNameFor(model => model.Name)
                    </th>
                    <th>
                        @Html.DisplayNameFor(model => model.Year)
                    </th>
                    <th>
                        @Html.DisplayNameFor(model => model.UpdateTime)
                    </th>
                    <th>
                        @Html.DisplayNameFor(model => model.CreateTime)
                    </th>
                    <th>
                        操作
                    </th>
                </tr>
            </thead>
            <tbody>
                @{
                    int index = 0;
                }
                @foreach (var item in Model)
                {
                    index++;
                    <tr>
                        <td>
                            @index
                        </td>
                        <td>
                            @Html.DisplayFor(modelItem => item.Name)
                        </td>
                        <td>
                            @Html.DisplayFor(modelItem => item.Year)
                        </td>
                        <td>
                            @Html.DisplayFor(modelItem => item.FormattedUpdateTime)
                        </td>
                        <td>
                            @Html.DisplayFor(modelItem => item.FormattedCreateTime)
                        </td>
                        <td>
                            <a asp-action="Edit" asp-route-id="@item.FormId"><i class="bi bi-pencil"></i></a>
                        </td>
                    </tr>
                }
            </tbody>
        </table>
    </div>
</div>